### PR TITLE
Date boundary validations

### PR DESCRIPTION
**Pull request by zarocknz**
Hi. Created some date validations using relative time strings (like PHP's strtotime) to use on forms when, for example, need the date of birth of a person to be 18 years or older. See the updated readme for other examples.

@spekulatius has asked me to create this pull request so he can discuss with you.

Cheers,
DouG.

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello Doug and Shea,

Nice work Doug! Looks good! I'll like that you adding in examples to explain this more :)

There are a few minor things I'd like to add/adjust. For example I would add a link to http://strtotime.co.uk/ to allow users to verify their expected strings. This helps to figure out what strtotime exactly does.

I would also add PHP 5.3.2 to the requirements in the composer.json - simply because of all the variations in strtotime before 5.3.2. Between 5.3.2 and 5.3.28 (used on strtotime.co.uk) shouldn't be any major changes.

Regarding 32 bit and 64 bit: Its only 2016 now, but 2038 isn't too far off. Especially when using longer + or - ranges. It would be good to deal with this case on 32 bit systems somehow. PHP_INT_SIZE is 4 on 32 bit and 8 on 64 bit systems. I'm just not sure how I'd add this in here. As a notice? What do you think @sheadawson ?

Peter

**Comment by zarocknz** [comment]
Hi @sheadawson, have you had a chance to look at this? Would be keen to get this merged in soon if you are OK with new validation. Thanks.

**Comment by sheadawson** [comment]
Sorry I haven't had a chance to look or test this. And won't for a while, bogged down at the moment. If you are able to add some unit tests for this to the existing https://github.com/sheadawson/silverstripe-zenvalidator/blob/master/tests/ZenValidatorConstraintTest.php I will be able to see that it works and how it works easily and will merge when it looks to be working well.

**Comment by lekoala** [comment]
if you don't mind, I suggest to close this. I'm not sure there will be more work done on the SS3 version or your changes are very likely to not fit the future changes on this module.

**Comment by zarocknz** [comment]
Sure, no worries :)

**Pull request closed without merging**
