### PR TITLE
Allow use of newer versions

### PR DESCRIPTION
**Pull request by lekoala**
Currently we are stuck on the version 2.0.7. Officially, the newer versions are compatible only with jQuery >= 1.8, therefore it might be dangerous to use parsley with the jQuery version bundled with SilverStripe (1.7.2).
Also, the current version requires a few "hacks" to make some functionnalities work like:
- remote validation error messages
- which button has been clicked

I added in this pull request the new version of parsley. With the yml config, we can choose the use the older version (and avoid any incompatibilities) or use the new one.

This is probably a very safe way to have both versions and avoid any BC breaks.

However, we can also decide to use only parlsey versions 2.4+ but I think it's your call :-)

I also fixed a small issue with extra validators that could cause js errors because of the extra validator being loaded before parsley.

### CODE REVIEW

**Comment by sheadawson** [comment]
Nice one! Could you rebase and I'll merge

**Comment by lekoala** [comment]
I was thinking of simplifying things a bit : having only a "legacy" (2.0.7) and "current" (whatever parsley is at the moment) version. When chosen, we could drop legacy altogether.

**Comment by sheadawson** [comment]
Sounds good!

**Comment by lekoala** [comment]
OK ! since you are on board, I've pushed on master the updates. I enabled by default the new version because I think it makes more sense (the only downside is that jquery is not added by default now, but I guess everyone is using a more up to date version anyway for frontend works).

I updated the docs accordingly

**Pull request closed without merging**
