### PR TITLE
remove trailing spaces

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @sheadawson 

I'm doing some clean up in a bunch of modules I'm using. Mainly zenvalidator, shortcodable, linkable and quickaddnew. If you want you could add me as a contributor and I'll merge all minor changes myself in. I won't merge any big changes without your double checking of course.

Peter

**Comment by sheadawson** [comment]
Cool thanks :)

**Comment by spekulatius** [comment]
No problem. Just add me when the pull requests are too annoying.

**Comment by sheadawson** [comment]
I've added you just now

**Comment by spekulatius** [comment]
Cool :)

**Pull request merged**
